spring.datasource.url=jdbc:postgresql://dpg-d99ldueq1p3s73eh4sb0-a.virginia-postgres.render.com:5432/gamified_farming_db

spring.datasource.username=gamified_farming_db_user

spring.datasource.password=ZCEsWwfWo5TZ9wjaTAffeQ4rvm8AEXlI

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true