spring.datasource.url=jdbc:mysql://localhost:3306/gamified_farming
spring.datasource.username=root
spring.datasource.password=Madhu@2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false